### ISSUE TITLE
Feature Idea: Set working directory of command

### ISSUE THREAD

**Issue by pixelbrackets** [ptlis/shell-command#1]
Thanks for the package 👏

I have a feature idea: It would be nice to have an option to change the working directory of a command.

This way an app could stay in the current working directory, but execute a binary from within another directory. This is often useful when running multiple tools which require different (relative oder absolute) entry points themself.

**Comment by ptlis** [comment]
Hi @pixelbrackets, this library already supports specifying the current working directory via the [CommandBuilder::setCwd](https://github.com/ptlis/shell-command/blob/master/src/CommandBuilder.php#L208) method.

Is this what you need, or am I misunderstanding your request?

**Comment by pixelbrackets** [comment]
Ha, cool, thats it. Tested it and wrote a quick documentation PR :+1:
