### ISSUE TITLE
Composer v2.0 readiness

### ISSUE THREAD

**Issue by codesmithtech** [ptlis/shell-command#7]
Composer raises deprecation errors when installing the package. The main concern is that it states that some classes will no longer be autoloader when composer v2.0 hits. 

Not critical, however, as they only look like test classes.

`Deprecation Notice: Class ptlis\ShellCommand\Test\Mocks\MockProcessTest located in ./vendor/ptlis/shell-command/tests/Unit/Mocks/MockProcessTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.8/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ptlis\ShellCommand\Test\Mocks\MockCommandTest located in ./vendor/ptlis/shell-command/tests/Unit/Mocks/MockCommandTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.8/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ptlis\ShellCommand\Test\Mocks\MockCommandBuilderTest located in ./vendor/ptlis/shell-command/tests/Unit/Mocks/MockCommandBuilderTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.8/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ptlis\ShellCommand\Test\ProcessOutputTest located in ./vendor/ptlis/shell-command/tests/Unit/ProcessOutputTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.8/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
`

**Comment by ptlis** [comment]
👍 Should be sorted now.
