### ISSUE TITLE
Composer psr-4 Warning

### ISSUE THREAD

**Issue by Parviz-Elite** [ptlis/shell-command#8]
Class ptlis\ShellCommand\Test\Mocks\MockCommandBuilderTest located in vendor/ptlis/shell-command/tests\Unit\Mocks\MockCommandBuilderTest.php does not comply with psr-4 autoloading standard. Skipping.

localhost > MAMP > PHP 8.1.0 + Composer 2.2.3

**Comment by ptlis** [comment]
Thanks for the report. This issue has already been fixed in master, but I've not had a chance to cut a release containing that fix.

I'll see if I can get a new release out promptly.

**Comment by ptlis** [comment]
Hi, I've just realised that this is actually already fixed in 1.3.0; please update to that release and you will not see this warning.
